# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d4d0d0c6aaac53d3d83a8f37577e7b4624c87b075501857604119633e00af52760d8027217e5662c8496febc23f90d835b86c54b00a720e65e4338f8caf4f3c

test:
  secret_key_base: 305f87c1de0f70e0755baf44170598c08f176bfd95e93f2c19e088ea008ef8f04c64595915bba60da3a2e2476b9ad329c7a64d1ab27b8fe9bc2c6ce0c916e022

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
